version: 0.0
os: linux
files:
  - source: 793320899105.dkr.ecr.eu-west-2.amazonaws.com/petclinic_repo:Latest
    destination: /home/
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: ec2-user