version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $eu-west-2 | docker login --username AWS --password-stdin $709410011461.dkr.ecr.eu-west-2.amazonaws.com/backend-ocker
  build:
    commands:
      - echo Build started on 'date'
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:LATEST .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build complete on 'date'
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:$IMAGE .
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json

